-- Strength, and what it does not mean. See supabase/seed/astro_readings.sql for
-- the table's shape.
--
-- Shadbala and vimsopaka both answer "how fully can this graha act", and neither
-- answers "is that a good thing". The distinction is easy to lose once a page
-- prints a number, so it is written down rather than assumed.
--
-- Every passage carries its source. The column has been on the table since the
-- beginning and nothing wrote to it; a passage that says two authorities differ
-- is worth little without naming the books, and a reader comparing this site
-- against another calculator needs the citation more than the conclusion.
--
--   psql "$DATABASE_URL" -f supabase/seed/astro_readings_strength.sql

insert into astro_readings (topic, subject, condition, heading, points, note, source, sort_order) values
('strength', 'Strength and influence', 'general',
 'Strength is not the same as influence',
 array[
   'Strength is how fully a graha can act. Influence is what kind of effect it has: favourable, unfavourable or mixed. The two are separate questions and a strength table answers only the first.',
   'A natural malefic can be very strong. Nothing in Shadbala or vimsopaka bala discounts Saturn for being Saturn, and nothing should: the measure is of capacity, not of goodwill.',
   'What a strong malefic does with that capacity depends on what it is to the house in question. Aspecting a house it does not rule, it afflicts that house, and being strong makes the affliction more certain rather than less.',
   'Rulership is what turns the same graha into a different influence. A malefic sitting on or aspecting a house it owns is acting on its own affairs; the same malefic reaching a house it has no claim to is an intrusion.',
   'So a high total is never on its own a reason to expect good from a graha. It says the graha will act, fully and in its own nature. Whether that is welcome is read from ownership, from the house, and from what else touches it.',
   'The same holds in reverse: a weak benefic may promise more than it can deliver, which is why a promising yoga is still read alongside a strength measure rather than instead of one.'
 ],
 'What a high total does tell you follows below.',
 'Not stated in one place in the texts. It follows from reading the vimsopaka bands of Brihat Parashara Hora Shastra ch.7 vv.26-27 beside the benefic and malefic rules of ch.2 v.11 - the first grades every graha on one scale, the second says they are not alike.',
 700),

('strength', 'Strength and influence', 'magnitude',
 'What a high total does tell you',
 array[
   'The natural significations of a graha with a high vimsopaka bala will normally flourish. Strength of this kind is the graha having the means to act on what it stands for, and in the ordinary case it does.',
   'Two things qualify that "normally": placement by house, and affliction. A graha poorly placed, or badly afflicted, can carry a high total and still deliver little of it, because the strength was never the obstacle.',
   'Where a graha takes part in a favourable yoga, vimsopaka bala is the natural measure of how much to expect. A raja yoga gives position and a dhana yoga gives affluence; the strength of the grahas forming it is what says on what scale.',
   'So it is better read as magnitude than as direction. It scales whatever the graha was going to do rather than deciding what that is, which is why the same figure means opposite things on a benefic ruling a trikona and on a malefic reaching a house it has no claim to.',
   'That also explains why it is worth computing at all for a yoga that is already present. The yoga says what is promised and vimsopaka bala says how much of it the graha can actually carry.'
 ],
 null,
 'Brihat Parashara Hora Shastra ch.7, tr. R. Santhanam (Ranjan Publications). The scaling reading is how B. V. Raman applies strength to yogas throughout Three Hundred Important Combinations.',
 701),

('strength', 'Strength and influence', 'bands',
 'Why the classical bands say "favourable"',
 array[
   'Parashara puts the vimsopaka result in four bands, chapter 7, verses 26-27: below 5 the graha is "not capable of giving auspicious results", above 5 and below 10 it "will yield some good effects", up to 15 the effect is "mediocre", and above 15 it "will yield wholly favourable effects".',
   'Taken at face value that makes a high score good news for any graha whatever, which is not how the strength is used in practice.',
   'The reading that reconciles them is that the bands describe how fully the graha delivers what it has to deliver, not whether what it delivers is wanted. A graha below 5 cannot act on its promise; a graha above 15 acts on it completely.',
   'For a benefic ruling a good house those come to the same thing. For a malefic afflicting a house it does not own they do not, and the band label is the least useful part of the reading.',
   'This page prints Parashara''s words for the bands because they are his, and says here what they should not be taken to mean.'
 ],
 null,
 'Brihat Parashara Hora Shastra ch.7 vv.26-27, tr. R. Santhanam. The band labels quoted are Santhanam''s English; the reading offered for them is this site''s and is not his.',
 702),

('strength', 'Vimsopaka Bala', 'reading',
 'Reading a vimsopaka total',
 array[
   'Each division in the scheme carries a share of twenty points. The graha keeps a fraction of each share according to its dignity there: the whole of it in its own sign, 18/20 in a great friend''s, 15/20 a friend''s, 10/20 a neutral''s, 7/20 an enemy''s and 5/20 a great enemy''s.',
   'So the floor is 5 and the ceiling is 20. A graha in a great enemy''s sign in every single division still scores 5, not nothing, which is worth knowing before reading a low total as an absence.',
   'Moolatrikona keeps the same twenty as an own sign, so it adds nothing to a graha already in its own. It is still worth reading as a dignity rather than as a kind of ownership, because for one graha the two part company: the Moon''s moolatrikona is Taurus 3 to 30, and Taurus is Venus''s. Asked only of owners, the Moon scored fifteen as Venus''s friend while standing in her own moolatrikona. Exaltation has no rung at all, so an exalted graha scores by its relation to the lord of that sign.',
   'And in the rashi only. Moolatrikona is a span of degrees inside a sign, while a varga position is a place within a division stretched back across the whole thirty, so the degree a D60 reports is not a degree of any sign the graha stands in. Claiming it there is meaningless, which is what this site did in about one varga cell in forty until the figures were checked against another calculator.',
   'The scheme has to be named alongside any figure. The same chart gives four different totals across the Shadvarga, Saptavarga, Dasavarga and Shodasavarga, because each shares the twenty points out differently, and a total quoted without its scheme cannot be checked.',
   'Each share-out has its own place in chapter 7. The Shadvarga and the Saptavarga are given at verses 17-19, the Dasavarga at verse 20, and the Shodasavarga at verses 21-25 - which is also where the varga viswa fractions above are given, the four bands following at verses 26-27.',
   'It measures dignity across divisions and nothing else. It does not know which houses the graha rules, where it sits, or what aspects it, so it is one input to a judgement rather than the judgement.'
 ],
 'What a high total does and does not mean is set out under Strength and influence.',
 'Brihat Parashara Hora Shastra ch.7 vv.17-27, tr. R. Santhanam. Unlike Shadbala, vimsopaka bala has no competing modern working: the verses are followed directly.',
 703),

('strength', 'Vimsopaka Bala', 'limits',
 'What vimsopaka bala cannot see',
 array[
   'It is tempting to treat the total as a complete account of a graha''s strength, since it is a single number that looks like one. It is not. It counts dignity division by division and nothing else, and three things the tradition counts as strength fall outside it entirely.',
   'Vargottama. The score reads each division on its own and never compares two, so a graha holding the same sign in the rashi and the navamsha is scored exactly as one holding two different signs of equal dignity. The repetition, which is the whole of what vargottama is, does not register.',
   'Parivartana. The score judges a graha against the lord of the sign it occupies and never asks what that lord is doing. An exchange strengthens both grahas and leaves the total untouched.',
   'Directional strength. Dig bala turns on which house a graha stands in - Jupiter and Mercury strongest on the ascendant, the Sun and Mars on the 10th, Saturn on the 7th, the Moon and Venus on the 4th - and vimsopaka never looks at houses at all.',
   'Neecha bhanga. A debilitated graha scores near the floor, and rightly so where the debilitation stands. Where it is cancelled the graha is not weak at all, and the total says otherwise: this is the case where the score is not merely blind but actively lowest exactly where it matters most that it should not be.',
   'The raja yoga form makes that sharper again. A cancelled debilitation in a kendra or a trikona is read as a strength that arrived by way of a weakness, and there is nothing in a division-by-division count of dignity that could ever express such a thing.',
   'None of these is an oversight to be patched into the total. They are separate measures, and the classical practice is to read them beside it rather than fold them in.',
   'On this page: vargottama is marked [V] beside the graha in the chart; an exchange and a cancelled debilitation are both reported among the yogas; and dig bala is a column of its own in Shadbala, which is the broader instrument and carries it as one of its six.'
 ],
 null,
 'Brihat Parashara Hora Shastra ch.7 for what the score counts; dig bala from ch.27 and B. V. Raman, Graha and Bhava Balas §§41-45. That these four fall outside the total is an observation about the scheme rather than a claim any of the three texts makes.',
 704),

('strength', 'Vimsopaka Bala', 'exclusions',
 'Who the count leaves out, and who stands in',
 array[
   'Rahu and Ketu are not scored. The whole measure is a relation to the lord of the sign a division gives - own sign, friend, enemy - and the nodes own no sign and keep no friendships, so there is no relation to take. A row for them would be blank in every column and totalled in none.',
   'That is not the same as saying they have no dignity. Raman gives them exaltation signs, which this site follows, and those are read where exaltation is read. It is friendship they lack, and friendship is what vimsopaka counts.',
   'The trimsamsa is the one division where a graha can be asked about a lordship that does not exist. Parashara gives its five lords as Mars, Saturn, Jupiter, Mercury and Venus in an odd sign and the reverse in an even one, ch.6 verses 27-28. Neither luminary appears: the Sun and the Moon rule no trimsamsa at all.',
   'So in D30 the Sun is judged as Mars would be and the Moon as Venus would be, which is what lets a luminary hold a trimsamsa of its own rather than being a guest in every one of them.',
   'The substitution is for ownership only. Everything else about the two - their exaltation, their debilitation, their friendships with the other grahas - is read as the Sun and the Moon, not as their stand-ins.'
 ],
 'The nodes'' exaltation signs are set out under Dignity.',
 'Trimsamsa lords from Brihat Parashara Hora Shastra ch.6 vv.27-28. The nodes'' exaltation signs are Raman''s, in Hindu Predictive Astrology; Parashara assigns the nodes none, which is itself one of the places the authorities part. The luminaries'' stand-ins in D30 follow from the lord list rather than from a rule any text states.',
 705),

-- Shadbala. The panel prints fifteen rows and a verdict; what a reader cannot
-- get from the panel is what each share is measuring, what the verdict is
-- measured against, which of the figures rest on a reading another authority
-- contradicts, and which books those authorities are. Those four go here.

('strength', 'Shadbala', 'general',
 'What the six strengths are',
 array[
   'Shadbala is six separate measures of a graha added into one figure, given in shashtiamsas, of which sixty make a rupa. Parashara sets it out in chapter 27 and B. V. Raman''s Graha and Bhava Balas is the standard English working of it.',
   'Sthana bala, positional. How far the graha stands from its own debilitation point, how it relates to the lord of the sign it takes in each of seven divisions, whether it sits in the odd or even sign and navamsa it prefers, whether it holds an angle, and whether it holds the third of a sign that matches its sex.',
   'Dig bala, directional. Each graha has one angle it is strongest on and is worth nothing opposite it: Jupiter and Mercury the ascendant, the Sun and Mars the 10th, Saturn the 7th, the Moon and Venus the 4th. The arc between the graha and its powerless point, divided by three. The powerless point is the middle of the bhava rather than the start of a sign, which is what makes a figure like 0.88 possible - a graha can sit almost exactly on it.',
   'Kala bala, temporal. Eight parts, and a ninth where there is a planetary war: day or night, the lunar fortnight, the third of day or night, the lords of the year, month, weekday and hora, and declination. All nine are checked against a textbook by two of K. N. Rao''s students, which works three charts through them: the totalled columns come out within a quarter of a virupa.',
   'Cheshta bala, motional. Strength from how the graha is moving, which is greatest near retrogression. The Sun and the Moon never retrograde, and Parashara gives them a rule in each of two chapters: at 27.18 they borrow, the Sun his ayana bala and the Moon her paksha, while at 28.3-4 each has a kendra of its own - three signs added to the sayana Sun for him, her distance from the Sun for her. This site takes the second, and leaves the figure out of the total, which is how Raman tabulates it.',
   'Parashara gives two ways to reckon it, in consecutive verses, and they are not the same quantity. Verses 21-23 name eight motions and allot them 60, 30, 15, 30, 15, 7.5, 45 and 30. Verses 24-25 then give arithmetic: the mean and true longitudes averaged, taken from the seeghrocha, divided by three. Raman follows the arithmetic and Charak gives only the motions. This site defaults to the arithmetic, because it is the verse that states a computation, and offers the other under Chart settings.',
   'Take the eight motions from Sripatipaddhati rather than from those verses. Mantreswara sends the reader there for the working at Phaladeepika IV.24 and Raman credits the same author for the kendra, so it stands behind both. Its list carries the same eight figures in the same order, and shows why the translated verses read so oddly: the fourth motion is samagama, conjunction with the Moon, which is not a speed at all. With a non-speed in that slot the speed names shift by one, and sama - the ordinary middling motion, which does not appear in Sripati - is left holding the smallest figure in the set. The eight are vakra 60, anuvakra 30, vikala 15, samagama 30, manda 15, mandatara 7.5, seeghra 45 and seeghratara 30.',
   'Sripati also supplies the boundary the other texts leave out, and it is the mean motion itself: manda and mandatara fall below it, seeghra and seeghratara above, and each pair is divided by whether the speed is still rising or already falling. Nothing needs banding by hand. Two things still do have to be chosen - how near to nothing a motion must be to count as vikala, and how close counts as conjunct for samagama - and both should be declared rather than buried. The two measures correlate at 0.25, which is to say they are different quantities rather than two roundings of one.',
   'Naisargika bala, natural. A constant per graha, the same in every chart, running from the Sun''s sixty down to Saturn''s 8.57 in order of brightness.',
   'Drik bala, aspectual. What the benefics aspecting the graha are worth less what the malefics are, quartered. The only share that can be negative.',
   'Rahu and Ketu are outside all of it. Shadbala is reckoned for the seven grahas only.'
 ],
 'What a high total does and does not mean is set out under Strength and influence.',
 'Brihat Parashara Hora Shastra ch.27 and ch.28, tr. R. Santhanam; B. V. Raman, Graha and Bhava Balas, chapters II to VIII. Mantreswara''s Phaladeepika treats the whole subject in one chapter, Adhyaya IV, and at sloka 24 refers the reader to Sripatipaddhati for the working - which is where the eight motions here come from, slokas 16.5-18, tr. V. Subrahmanya Sastri.',
 706),

('strength', 'Shadbala', 'reading',
 'What a Shadbala total is measured against',
 array[
   'The requirement differs by graha, so a total is only ever read against its own minimum and never against another graha''s. Raman gives them as 300 shashtiamsas for the Sun, 360 for the Moon, 300 for Mars, 420 for Mercury, 390 for Jupiter, 330 for Venus and 300 for Saturn - five, six, five, seven, six and a half, five and a half and five rupas.',
   'That is why Mercury so often reads weak. It is asked for more than any other graha, and a total that would make the Sun comfortably strong leaves Mercury short.',
   'The Sun''s figure is the one that is disputed, and the dispute is not small. Parashara''s verse 32-33 gives the seven requirements as 390, 360, 300, 420, 390, 330 and 300, putting the Sun at 390 rather than 300; Mantreswara, writing independently, gives the Sun six and a half rupas as well. Raman''s 300 is the minority reading. This site uses it, and the ratio chart is where the choice shows: at 300 the Sun leads that chart in 96 charts in a hundred and at 390 in 65, and the graha standing highest changes in about a third of charts.',
   'There is a second set of minimums that the panel does not print. Chapter 27 verses 34-36 give a required figure for each share separately, by group: Jupiter, Mercury and the Sun want 165 sthana, 35 dig, 50 kala, 112 cheshta and 30 ayana; the Moon and Venus want 133, 50, 30, 100 and 40; Mars and Saturn want 96, 30, 40, 67 and 20.',
   'Santhanam''s note on those verses is that meeting them makes a graha considerably favourable even where the total falls short of the overall requirement. Read the other way, a graha can clear its total while failing several of its parts, which is worth knowing before a single verdict is trusted.',
   'A war changes the total. Where two of the five starry grahas stand within a degree of each other the loser gives strength to the winner, and a graha''s verdict can turn on it.'
 ],
 'The war is set out under Yuddha bala.',
 'B. V. Raman, Graha and Bhava Balas §122 and the table at p.110; Brihat Parashara Hora Shastra ch.27 vv.32-36, tr. R. Santhanam; Mantreswara, Phaladeepika IV.22-23, tr. V. Subrahmanya Sastri. Why Raman''s Sun is preferred over the two classical figures is set out under Where the teachings differ.',
 707),

('strength', 'Yuddha bala', 'general',
 'Planetary war, and why the answer is small',
 array[
   'Two grahas within one degree of each other are at war. Only the five starry grahas fight - Mars, Mercury, Jupiter, Venus and Saturn - and the Sun and the Moon never take a side. It happens in about one chart in twelve.',
   'Raman gives the victor as the graha of lesser longitude, sections 76 and 77. Parashara''s chapter 79 instead makes Venus the victor always and otherwise the more northerly graha the victor, which is a different rule and disagrees about who won in half of all wars.',
   'The size of the correction is where the two readings part company entirely. Chapter 27 verse 20 says the difference between the two Shad-balas is added to the victor and deducted from the vanquished, and taken at that the correction reaches 272 shashtiamsas - more than four rupas, more than any graha''s whole requirement. Where the victor happened to be the weaker of the two, the pair simply exchange totals.',
   'Raman divides that difference by the difference between the diameters of the two grahas'' discs, which he tabulates as 9.4 for Mars, 6.6 for Mercury, 190.4 for Jupiter, 16.6 for Venus and 158.0 for Saturn. The same war that moved 117 shashtiamsas each way under the bare verse moves 0.7 under Raman.',
   'The disc diameters are the whole of the difference, and the bare verse does not mention them. A war between Jupiter and Saturn, whose discs are both large and close in size, is divided by a small number and so counts for more; a war between Mercury and Mars, whose discs are small and closer still, counts for more again; a war between Jupiter and Mercury is divided by almost the full 190 and nearly vanishes.',
   'This site follows Raman. A calculator that applies the difference raw will disagree sharply on any chart that holds a war, and one that omits yuddha bala altogether will disagree in the other direction.'
 ],
 'The aggregate compared is sthana, dig and kala as far as hora bala, so ayana and the war itself stay out of it.',
 'B. V. Raman, Graha and Bhava Balas §§76-77, including his table of disc diameters; Brihat Parashara Hora Shastra ch.27 v.20 for the correction and ch.79 for the victor, tr. R. Santhanam.',
 708),

('strength', 'Drik bala', 'general',
 'Aspect strength, and the shape of a drishti',
 array[
   'Drishti is not a thing a graha either casts or does not. It rises and falls with the exact angle between two grahas, and Raman gives the curve in sections 114 and 115, from Sripathi, noting that Parashara gives the same rules.',
   'It is nothing at 30 degrees, fifteen at 60, forty-five at 90, thirty at 120, nothing again at 150, sixty at 180, and falls away to nothing at 300. Between those points it moves in straight lines, so a graha''s drishti changes with every degree it travels.',
   'The familiar table - a quarter aspect on the 3rd and 10th, a half on the 5th and 9th, three quarters on the 4th and 8th, full on the 7th - is that curve read off at the cusps and nowhere else. It is exact at seven points of the circle and an approximation everywhere between them.',
   'Visesha drishti, the special aspect, adds to the ordinary value rather than replacing it: fifteen more for Mars on the 4th and 8th, thirty for Jupiter on the 5th and 9th, forty-five for Saturn on the 3rd and 10th. Each brings the total to exactly sixty at the cusp, which is why replacing it with sixty looks right until a graha is anywhere but the cusp.',
   'The drishti pinda is the sum of all of it over one graha, benefic aspects positive and malefic negative. Drik bala is a quarter of that pinda, and nothing else. Santhanam''s verse 19 adds "super add the entire aspect of Mercury and Jupiter"; Raman''s section 120 has no such clause, and his worked examples rule it out.',
   'Those examples are worth knowing about, because they are the only place in the whole of Shadbala where an authority shows his working for all seven grahas at once. Example 54 gives the drishti pinda on each graha of his Standard Horoscope, with his own benefic set printed beside it - Jupiter, the Moon and Venus benefic, the Sun, Mars, Saturn and a combust Mercury malefic - and Example 55 divides each by four. This site reproduces all fourteen of those figures to within 0.05 virupas, which is his rounding of the positions.',
   'The definition also puts a ceiling on the answer, and the ceiling is the most useful thing here for anyone comparing calculators. Since drik bala is a quarter of a signed sum, its size can never exceed a quarter of the unsigned sum of the drishti falling on that graha. That bound can be computed for any chart, and it depends on the positions alone: no reading of who is benefic can push a figure past it.',
   'That turns a vague disagreement into a decidable one. Checked against one widely used program over three charts, 9 of its 21 figures stood above the ceiling the definition allows, by as much as 26 virupas, and its figures correlate with these at 0.10 - which is to say not at all. So the difference was never about the Moon''s nature or Mercury''s company, which is where such a search naturally starts and where a good deal of effort went. A quantity that breaks the bound is not this quantity under another reading; it is a different measurement wearing the same name, and the two should not be compared at all.',
   'The practical consequence is worth stating, because it does not stay inside this row. That program''s aspect figures average about 31 virupas where these average 2, so its Shadbala totals will run roughly half a rupa per graha higher, which is enough to move verdicts. Two totals built on different aspect measures are not close readings of one quantity and there is no reconciling them by argument.'
 ],
 'It is the one share that can be negative, so a graha can lose strength by being looked at.',
 'B. V. Raman, Graha and Bhava Balas §§114-115 for the curve, which he takes from Sripathi, §120 for the quarter, and Examples 54 and 55 for the worked table this site is checked against; Brihat Parashara Hora Shastra ch.27 vv.14-19, tr. R. Santhanam. Sripatipaddhati is read directly elsewhere on this site, for the cheshta material, in V. Subrahmanya Sastri''s translation; its chapter II carries this curve too, at slokas 1-4, but the implementation here still descends from Raman and has not been re-derived from those slokas.',
 709),

('strength', 'Paksha bala', 'general',
 'The fortnight, and the Moon''s own place in it',
 array[
   'Paksha bala asks how far into the bright or the dark half the birth fell. Subtract the Sun''s longitude from the Moon''s, reduce anything over 180 by taking it from 360, and divide by three: that figure goes to every benefic, and sixty less it goes to every malefic. One number for each group, not one for each graha.',
   'So it is not a measure of the Moon. It is a measure of the fortnight, and what the fortnight does for the two kinds of graha is opposite: a bright half strengthens the benefics and a dark half strengthens the malefics.',
   'Two questions about the Moon then have to be settled, and only one of them is contested. Uncontested: the Moon''s figure is doubled. Raman states it as rule (c) of section 55, "Chandra''s Paksha Bala is always to be doubled", and Santhanam''s note to verses 10-11 says the same in as many words, adding that it holds whether she is counted a benefic or not.',
   'Contested: which group she joins. Santhanam reads the "decreasing Moon" of chapter 2 as the dark half, which puts the boundary at opposition. Raman fixes it at the eighth day either side - benefic from the eighth of the bright half to the eighth of the dark half - and says so inside the paksha bala chapter itself, at section 53, so it is the rule he means to govern this row. This site follows Raman.',
   'Together the doubling and the group rule produce a result that looks wrong and is not: a thin Moon ends with more paksha bala than a half-lit one, because she has joined the malefics and taken the complement.',
   'There is a second reading, that she is always a benefic and so takes the brightness outright whatever her phase. K. S. Charak lists her among the natural benefics for this bala with no qualification attached, which is the whole of the case for it: no classical text says so.',
   'It was argued here from Phaladeepika IV.5 as well - "The Moon is strong and auspicious when she has her full Paksha bala" - on the ground that a full paksha bala for the Moon means a dark Moon under the group rule. That was wrong, and worth setting out because it is the kind of mistake a plausible sentence can carry for a long time. Under the group rule she is a benefic through the bright half, so her figure rises with her light and reaches 119.5 of a possible 120 at the full Moon. The sloka describes the group rule rather than contradicting it. (She scores nearly as high at the new Moon, 117.8, having joined the malefics and taken the complement - which is the genuinely odd consequence, and a separate point.)',
   'Phaladeepika in fact states the group rule itself, in the sloka that enumerates the six strengths. IV.1: "In the bright-half of a month the benefics, and in the dark-half, the malefics, are strong." Varahamihira has it too, in the oldest of these texts, Brihat Jataka 21: "The malefic and benefic planets have strength (Pakshabala) in the dark and bright halves of the month respectively."',
   'The disagreement is about what paksha bala measures. If it measures what the fortnight does to a graha, the Moon is a graha like the rest and takes her turn in the groups. If it measures the Moon''s own condition, her brightness is the answer and the groups are beside the point. Four texts take the first - Brihat Jataka and Phaladeepika on what the measure is, Santhanam, Raman and Uttara Kalamrita on where she falls within it - and none takes the second. So this site takes the first, on Raman''s boundary, and offers the second under Chart settings, because software computes it and the choice changes her figure by up to sixty.',
   'One position that no authority consulted here holds: reporting her brightness undoubled. That agrees with neither reading, since Santhanam, Raman and Charak all apply the doubling.',
   'The doubling is why this row carries two ceilings. Sixty bounds it for six grahas and a hundred and twenty for the Moon. Chart settings can show her figure halved, which is how some software prints it and makes a row-by-row comparison easier; that changes the display only, and the total still counts the doubled value.',
   'It used to reach further than its own row, and no longer does. Chapter 27 verse 18 makes the Moon''s cheshta bala her paksha bala, so whichever reading was taken showed up twice in the same table. Chapter 28 verses 3-4 gives her a cheshta kendra of her own instead - the Sun''s longitude deducted from hers - and Raman writes that out separately at his section 137 rather than pointing back at paksha bala, which he would have had no reason to do if verse 18 settled it. This site follows the kendra, so the two rows are now independent.',
   'The two agree only while she is read as a benefic, her paksha bala then being that same arc over three. Under the group reading a thin Moon takes sixty minus it, and the pair become complements: a Moon showing 37 in one row shows 23 in the other. That is not a contradiction to go looking for a fault in. Raman''s own chart has her past the eighth day, where Example 18 and Example 61 both give 43.46, which is why the identity at verse 18 never troubles him.'
 ],
 'The Sun''s ayana bala is doubled for the same reason and in the same way.',
 'For the group reading: B. V. Raman, Graha and Bhava Balas §§52-55 with his Example 18, and Brihat Parashara Hora Shastra ch.27 vv.10-11, v.18 and ch.2 v.11 with Santhanam''s notes. For the other: K. S. Charak, Elements of Vedic Astrology, under Kaala Bala, which lists the Moon among the natural benefics and directs that her figure be doubled; and Mantreswara''s Phaladeepika IV.5 and IV.21, tr. V. Subrahmanya Sastri.',
 711),

('strength', 'Cheshta bala', 'general',
 'What motion is being measured, and whose',
 array[
   'Cheshta means effort, and what the measure rewards is a graha working against the ordinary run of its motion. It is greatest at retrogression and least where the graha runs fastest and straightest. Mantreswara puts the whole of it in a line at Phaladeepika IV.2: "The Moon gets Cheshtabala when she is full. The Sun gets it when he is in his northern course; the other planets, when in their retrograde motion."',
   'For the five it is computed from the chesta kendra, and the texts are agreed on what that is. Sripatipaddhati says it outright: the cheshta kendra "is identical with the Seeghrakendra", the arc of the seeghra correction in Indian planetary theory. Uttara Kalamrita says the same in passing, that the planets "taken in their regular order from Mars" have their cheshta bala "calculated from the degrees in their respective Sighra Kendras". Reduced past six signs and divided by three.',
   'Reaching that arc is another matter. Sripatipaddhati''s translator calls the method "very elaborate", involving "a good knowledge of the laws of planetary motion, their Manda and Seeghra phalas", and Raman calls his own alternative "a simple method" at section 83 in as many words. The shortcut both then give is Kesava Daivagna''s line: "The Cheshtakendra of the planets, Mars, etc., is their Sighrochcha diminished by half the sum of their mean and true positions." Averaging the mean and true longitudes stands in for the manda-corrected place the real arc is measured from.',
   'The two part company, and one worked example settles which is which. Sripati prints accurate kendras for his own 1853 chart, taken from Ketakar''s tables: Mars 325.989, Budha 217.059, Guru 216.760, Sukra 351.085, Sani 11.270. Computing the seeghra kendra itself reproduces those to 0.34 of a virupa; the shortcut averages 3.41 and misses Budha by eight, his manda correction being the largest of the five. Against Raman''s Example 51 the order reverses, 0.04 against 1.74, because his examples are computed with the shortcut. Neither is simply better - each answers to the book that uses it - which is why this site offers both and defaults to the arc the texts define.',
   'Which longitude plays the seeghrocha depends on the kind of graha, and that is the whole of the difficulty. An outer graha turns retrograde at opposition, so the Sun''s mean longitude is its seeghrocha and the kendra is near enough its elongation. An inner one turns at inferior conjunction, where its elongation is almost nothing; there its own mean longitude is the seeghrocha and the Sun''s stands in as its mean. Raman''s Example 49 shows it plainly, Budha and Sukra both worked with 181.23, the Sun''s mean, where Kuja, Guru and Sani use their own.',
   'A mean longitude is not an observation. It is a construct of whichever model defines it, so measuring a modern true longitude against a modern mean is self-consistent without being what any text computes. Raman pairs an accurate ephemeris with the Surya Siddhanta tables, and that pairing is what reproduces his worked answers.',
   'The luminaries never retrograde and so have no arc to measure. Parashara answers twice: at 27.18 they borrow, the Sun his ayana bala and the Moon her paksha, and at 28.3-4 each is given a kendra of its own, three signs added to the sayana Sun for him and the Sun''s longitude deducted from hers for her. Raman writes both out separately at his sections 136 and 137, which he would have had no reason to do if verse 18 settled it.',
   'His table then leaves both rows empty. Example 56 prints totals that are the sums without them - Chandra''s 389.80 to the hundredth - and section 136 says why the figure is wanted at all: it is "necessary to ascertain the Ishta and Kashta Phalas", which is the business of chapter 28. Under the borrowing reading there is an arithmetical reason to agree, since the Sun''s ayana bala is already inside his kala bala and doubled there.',
   'Whatever is decided about the luminaries, the five carry the measure, and it is worth reading their figures as the phase of a cycle rather than as a score. A graha near sixty is at or close to opposition and turning; a graha near nothing has just passed the Sun and is running at its quickest.'
 ],
 'The eight motions Parashara offers as an alternative are set out under Shadbala.',
 'Mantreswara''s Phaladeepika IV.2, tr. V. Subrahmanya Sastri; Sripatipaddhati slokas 16.5-18, same translator, quoting Kesava Daivagna; Uttara Kalamrita slokas 16.5-17.5; Brihat Parashara Hora Shastra ch.27 v.18 and ch.28 vv.3-4, tr. R. Santhanam; B. V. Raman, Graha and Bhava Balas §§79-107 with Examples 49-51, and §§136-137 with Examples 60-61.',
 717),

('strength', 'Nata-Unnata bala', 'general',
 'Which midnight, and whose clock',
 array[
   'Nata is the birth time measured back to the nearer midnight, deducted from thirty ghatis and doubled. The Moon, Mars and Saturn take it and are strongest at midnight; the Sun, Jupiter and Venus take sixty less it and are strongest at noon; Mercury takes the full sixty at any hour.',
   'The arithmetic is simple and the trap is in the clock. Raman is explicit at section 48: "Midday of any place is the local noon when the Sun passes over its meridian. The Hindus consider the apparent noon ... if birth time is marked in local mean time, it must be converted into the apparent time by applying equation of time."',
   'That asks for two corrections, and a timezone makes neither. A zone is an administrative band, so a place can sit an hour or more from the meridian it keeps time by; and even on that meridian a clock keeps mean time, which the equation of time parts from the Sun by up to sixteen minutes either way.',
   'The cost is a function of geography rather than of astrology. At Delhi the two clocks differ by about 35 minutes, which is three virupas; at New York 70 minutes and six; at Vigo, on the western edge of a zone it shares with central Europe, 169 minutes and fourteen - a quarter of the range of the whole measure.',
   'This site reckons it by local apparent time: the hour angle of the true Sun at the birthplace, nothing at its lower meridian and twelve at its upper. Two births at the same clock time in two cities of one timezone will differ, which is the point.',
   'Chart settings offers the clock as well as the sundial, a row differing for that reason being easy to mistake for a difference of method. Drik Panchang reckons it by the zone, and on one chart checked that accounted for the whole of the difference between its nata-unnata row and this one. The default is the sundial, Raman asking for it by name. The clock is not unsupported, though it once said so here: Uttara Kalamrita''s own working takes it, "It is enough if we take 12.00 hours as noon and zero hours as midnight", so the choice is between two readings rather than between a reading and a convenience.'
 ],
 null,
 'B. V. Raman, Graha and Bhava Balas §47 for the measure and §48 for the clock, quoted above; Brihat Parashara Hora Shastra ch.27 vv.6-7, tr. R. Santhanam; Uttara Kalamrita, tr. V. Subrahmanya Sastri, for the measure itself and for the clock it allows.',
 712),

('strength', 'Shadbala', 'limits',
 'Where the teachings differ, and what this site chose',
 array[
   'Shadbala looks like arithmetic and is partly interpretation. A dozen of its figures rest on a reading that some other authority contradicts, and a total is only as settled as the choices behind it. Two figures from two calculators that disagree are not evidence that one is broken; they are usually evidence that they read different books. These are the places it happens.',
   'The saptavargaja ladder. Raman''s section 30 gives 45 in moolatrikona and 30 in an own sign, then 22.5 in a great friend''s varga, 15 in a friend''s, 7.5 in a neutral''s, 3.75 in an enemy''s and 1.875 in a great enemy''s. Parashara''s own verses - chapter 27 shlokas 2-4, not a translator''s note - give 20, 15, 10, 4 and 2 for those lower five instead. The two differ by about five shashtiamsas on average and move one verdict in forty.',
   'What the ladder cannot reach is worth knowing with it. Moolatrikona counts in the rashi alone, so the most a graha can take is 45 once and an own sign''s 30 in each of the other six vargas: 225, not the 315 that seven moolatrikonas would suggest. Sthana bala follows, capping at 390 rather than 480. Sarajit Poddar sets both out in his paper on Shadbala, and this site printed the larger pair for a long time, which made every graha look weaker against the scale than it was - the highest saptavargaja in twelve hundred charts, 217.5, showed as 69 per cent of the column where it is 97.',
   'What the ladder cannot reach is worth knowing beside it. Moolatrikona counts in the rashi alone, so the most a graha can take is 45 once and an own sign''s 30 in each of the other six vargas: 225, not the 315 that seven moolatrikonas would suggest, and Sthana bala follows at 390 rather than 480. Sarajit Poddar gives both figures in his paper on Shadbala. This site printed the larger pair for a long time, which cost nothing in the arithmetic and a good deal in the reading: the highest saptavargaja in twelve hundred charts, 217.5, showed as 69 per cent of its column where it is 97.',
   'The ladder is now checked rather than argued. A textbook on Shadbala by two of K. N. Rao''s students works three charts through the positional strengths and prints the longitudes it starts from, which makes them the first real check available: Raman''s Example 9 gives only totals, and no classical text works saptavargaja at all. It states the halving ladder outright, with "Mool Trikon is seen only in D-1" beside it, over D-1, D-2, D-3, D-7, D-9, D-12 and D-30, and takes the compound friendship from the rashi chart. This site reproduces all forty-nine cells of its third example and forty-eight of its first.',
   'The forty-ninth is the book''s slip, and worth setting out because it shows how the compound friendship has to be built. Its panchadha table puts the Moon among Mars''s friends, worth 15, where its own three rules make her a fast friend at 22.5 - the natural table has the Moon among Mars''s friends, the temporal table has her there too, and friend plus friend is given as fast friend. Mars''s other five relationships all agree. Two of its arithmetic tables also carry slips a reader can catch without any of this: an uchcha bala of 71.43, which the measure cannot reach, and a row that misses its own total by fifteen.',
   'This site uses Raman''s, and it is better attested than his name alone suggests. Uttara Kalamrita prints the whole ladder as a table at slokas 3.5-5 - exaltation 60, moolatrikona 45, swakshetra 30, adhimitra 22.5, mitra 15, sama 7.5, satru 3.75, adhisatru 1.875 - which is Raman''s figures to the last decimal. Sripatipaddhati works its example in rupas and reaches the same place: three-eighths of a rupa for a great friend''s varga, a quarter for a friend''s, an eighth for a neutral''s. It records Parashara''s 45, 30, 20, 15, 10, 4, 2 as well, but as a commentator''s reading of the verses rather than as its own. Three witnesses to one, then, and Raman''s worked table for the Standard Horoscope could not be reconciled with any other ladder in any case.',
   'The Sun''s requirement. Parashara''s verse 32-33 puts it at 390 shashtiamsas and Mantreswara at six and a half rupas, which is the same figure arrived at independently; Raman''s section 122 says five, twice - in prose and in the table of Example 57. Two classical witnesses against one modern one is ordinarily decisive, and this is the one place the site goes the other way. The reason is that Raman''s number is load-bearing: his worked ranking of the Standard Horoscope calls the Sun the most powerful graha in it, which is true at 300 and false at 390, so adopting Parashara''s figure inside an otherwise Raman calculation would contradict the example the rest of the method is checked against. It is the most consequential open choice here - the graha topping the ratio chart changes in about a third of charts - and the least comfortable.',
   'Where moolatrikona counts. Raman restricts it to the rashi - "45 Shashtiamsas ... only when it is in its Moolatrikona Rasi, and not when it occupies any other of the 6 vargas" - and he is following Sripatipaddhati, which states the same restriction and then works it: the Sun, standing in the drekkana and saptamsa of his own moolatrikona sign, is given half a rupa in each for the sign being his own rather than three-quarters for its being his moolatrikona. The arithmetic agrees with both: moolatrikona is a span of degrees inside a sign, and a varga position is a place within a division stretched back across the whole thirty, so the degree a division reports is not a degree of any sign the graha stands in.',
   'Cheshta bala. Reckoned from the chesta kendra: the graha''s distance from its seeghrocha, nothing where that is nothing and sixty where it is a half circle. The seeghrocha differs by kind, and that is the whole of the point - an outer graha turns retrograde at opposition, so the Sun is its seeghrocha and the kendra is its elongation, while an inner one turns at inferior conjunction where its elongation is near nothing and its own mean longitude is the seeghrocha instead. A method that reads motion rather than the kendra gets the outer three about right and Venus badly wrong, for exactly that reason.',
   'Which mean longitudes it is measured against. A chesta kendra is the gap between a true longitude and a mean one; a true longitude is an observation, but a mean longitude belongs to whichever model defines it, so pairing a modern mean with a modern true is self-consistent without being what any text computes. Raman pairs an accurate ephemeris with the Surya Siddhanta tables at his sections 96-103, and that pairing reproduces his Example 51 to within 0.13 virupas on every graha. Modern mean longitudes miss Budha by 4.1, the two models putting his mean eleven degrees apart; the outer three scarcely move either way, the Sun''s error cancelling most of each graha''s own. This site takes the classical tables and offers the modern ones under Chart settings.',
   'Whether the luminaries'' cheshta bala is added at all. Parashara gives them one at 27.18 and lists cheshta among the six at 27.24-25, so summing it is a defensible reading. Raman does not: Example 56 leaves both rows of his table empty, and his printed totals are the sums without them, Chandra''s 389.80 to the hundredth. Section 136 says why the figure is wanted - it is "necessary to ascertain the Ishta and Kashta Phalas" - which is the business of chapter 28, not of the shadbala sum. There is an arithmetical reason to agree with him: under the 27.18 reading the Sun''s ayana bala already sits inside his kala bala, doubled, so counting it again puts it in at three times its base rather than twice, and the same for the Moon''s paksha. It is worth about a rupa on each.',
   'Which third of a sign each sex wants. Both English translations of Parashara give the same order - "Male, female and hermaphrodite planets respectively get a quarter Rupa according to placements in the first, second and third decanates" - which puts a female graha in the second drekkana and a neuter one in the third. Raman has it the other way at section 36, neuter in the middle and female in the last, and K. N. Rao teaches the same. Raman also works it, which the verse does not: Example 12 pays Sukra, a female graha in the third drekkana, fifteen, and pays Chandra, equally female, in the second, nothing. Under the translated verse both results would reverse. This site follows the practice, three sources deep, and reads the verse as a translator ordering a compound of the three sexes in its usual citation order rather than in the order the decanates take them. It is worth fifteen virupas to Budha, Sani, Chandra and Sukra.',
   'The Moon''s nature. Chapter 2 verse 11 names the "decreasing Moon" among the malefics and does not say where decreasing begins, and three readings of it are on record. Santhanam takes it as the dark fortnight, putting the boundary at opposition. Raman takes it as the thin Moon and fixes the boundary at the eighth day either side, which is 90 to 270 degrees of elongation. Santhanam''s own note preserves a third, the Yavanas'' by way of his translation of Saravali, page 70: very auspicious from 120 to 240 degrees. This site follows Raman - and the third witness is why. Raman''s rule and the Yavanas'' are the same kind of rule, a band of elongation centred on opposition differing only in width, and they agree in 83 charts in a hundred; the fortnight rule is a different kind of rule and agrees with Raman''s in 50, which is what agreement by coincidence looks like.',
   'Two clauses go with that choice. Santhanam''s notes add that a waning Moon conjunct or aspected by a benefic turns benefic, and that a waning Moon with Mercury makes both benefic. Both are his commentary rather than the verse and Raman carries neither, so neither is applied here.',
   'Mercury''s company. The verse says only that "Mercury is a malefic if he joins a malefic", and what joining means matters more for Mercury than for anyone: it is never more than about 28 degrees from the Sun and shares its sign in 44% of charts, so a same-sign test against the Sun reports Mercury''s orbit rather than its company. Raman''s footnote to his drik bala table fixes it - "Mercury is a malefic as he is very closely associated with Sun or combusted" - so the Sun is judged by combustion and every other malefic by the sign. The two tests disagree in 41% of charts, in both directions.',
   'Whether the qualifier is applied at all is a further question, and the answer from the books is that it is. Charak has "well-associated Mercury" among the natural benefics and "afflicted Mercury" among the malefics, on the ground that Mercury "behaves as a benefic under benefic influence and as a malefic under malefic influence". K. N. Rao calls Mercury a malefic in a worked chart "as he is associated with two malefics Sun and Ketu", and says of combustion generally that such planets "become evil". What some software computes instead is the same authors'' opening list - "Natural benefics: Moon, Mercury, Jupiter, Venus" - without the sentence that follows it. Chart settings offers both and defaults to the qualified reading, since none of the three defends the bare list as the whole rule.',
   'Which clock the day is measured by. Nata-unnata bala and the hora both turn on the time of day, and a timezone is not the time of day: it is an administrative band, and it keeps mean time where the rule asks for apparent. Raman asks for both corrections by name at section 48. At the western edge of a wide zone the difference reaches a quarter of nata bala''s whole range.',
   'The combustion orbs. Santhanam''s chapter 4 table and Raman''s Hindu Predictive Astrology section 54 agree on six of the seven and on every retrograde figure, and differ on Saturn alone - 16 degrees against 15. Raman''s is used.',
   'Yuddha bala. The bare verse adds the difference between two Shad-balas to the victor and deducts it from the vanquished, which reaches 272 shashtiamsas and can make a pair exchange totals outright. Raman divides that difference by the difference between the diameters of the two grahas'' discs, which the verse never mentions and which brings the median correction down from 83 to one. He also makes the victor the graha of lesser longitude where chapter 79 makes it the more northerly, and the two disagree about who won in half of all wars.',
   'Visesha drishti, and whether it is a matter of degrees or of signs. Santhanam settles it in degrees: Mars adds 15 "when the aspect angle is 90-120 degrees or 210-240", Jupiter 30 at 120-150 or 240-270, Saturn 45 at 60-90 or 270-300, and he adds that a house in aspect is taken at its cusp, "akin to a planetary degree". Applying the same additions by whole sign instead gives a different answer whenever a graha sits in one house by sign and another by degree, which is common; on one chart checked against Drik Panchang it was the whole of the difference between its drik row and this one, worth 7.5 virupas on the graha concerned.',
   'Drik bala. Santhanam''s verse 19 ends "super add the entire aspect of Mercury and Jupiter", which would add about 41 virupas on average. Raman''s section 120 is the quarter of the drishti pinda and nothing else, and his own worked example rules the clause out: his Sun takes a pinda of +63.45 and a drik bala of +15.86, the quarter exactly, with Jupiter among the grahas aspecting it. Not applied.',
   'Ayana bala, where two whole methods are on offer and the mistake is to take half of each. Raman''s section 75 gives Kesava Daivagna''s formula, the declination added to 24 degrees over 48, and his section 73 says where that declination comes from: the bhuja of the sayana longitude, read off a table of six fifteen-degree steps. The two halves belong together, because a declination derived from a longitude is exactly what tops out at 24.',
   'Parashara''s is the other whole method. Santhanam''s note to chapter 27 verses 15-17 gives the formula as the kranti added to 23 degrees 27 minutes, times 1.2793 - which is 23.45 over 46.9, the real obliquity in both places - and says plainly that "Krantis (or declinations) can be ascertained from standard modern ephemeris". A modern ephemeris gives the true declination, and for the Moon that includes her ecliptic latitude.',
   'The constants differ by at most 0.7 virupas, so they are not where the argument is. It is in which declination each belongs with, and the formula settles that rather than either author. 23 degrees 27 minutes is the obliquity, and the obliquity is the greatest declination a point on the ecliptic can have. So a declination read from the longitude alone is bounded by it exactly: the scale runs from nought to sixty, touching both ends and leaving neither. Measured over 1,800 charts it does precisely that, 0.00 to 60.00.',
   'No other pairing sits right. Raman''s 24 with the same declination never lets the formula reach the sixty it declares, 0.69 to 59.31. And a true declination carries the graha''s latitude, so the Moon passes 28 degrees and the scale breaks in both directions: minus 6.70 to 66.13 on Parashara''s constant, minus 5.86 to 65.30 on Raman''s. A negative strength is not a reading.',
   'This site defaults to Parashara''s constant with the declination taken from the longitude alone, for that reason, and offers the other three. It ran Raman''s constants against a true declination for a while, which is neither author''s method and cost the Moon about 3.9 virupas, as much as 6.6.',
   'Chart settings offers the other reading, and it is worth knowing which calculators take it. Drik Panchang scales the true declination and reproduces exactly on that setting; the difference reaches 2.5 virupas on a planet and 6.6 on the Moon. One caution for anyone checking a single chart: the Moon hides the question whenever she is near a node, her latitude being nil there, so a chart that agrees proves less than it appears to.',
   'None of these is a defect to be patched. They are places where careful authorities read the same verses differently, and the useful habit is to know which reading produced a figure before comparing it with a figure from somewhere else.'
 ],
 'What vimsopaka bala cannot see is a separate list, under Vimsopaka Bala.',
 'Brihat Parashara Hora Shastra chs.2 and 27 tr. R. Santhanam; B. V. Raman, Graha and Bhava Balas and Hindu Predictive Astrology; Mantreswara''s Phaladeepika tr. V. Subrahmanya Sastri; Saravali at second hand through Santhanam. The rule for choosing between them is under The books behind the numbers. Every percentage quoted here was measured on this site''s own engine over 1,800 or 18,000 charts and is a property of this implementation, not a claim from any text.',
 713),

('strength', 'Shadbala', 'sources',
 'The books behind the numbers',
 array[
   'Five works do the real work on this page, and they are not equal in kind: two are classical Sanskrit texts and three are twentieth-century workings of them. Where they conflict there is a standing order of precedence, and it is worth stating plainly, because it explains nearly every figure another calculator will disagree about.',
   'Brihat Parashara Hora Shastra, in R. Santhanam''s translation for Ranjan Publications. The parent text. Shadbala''s six shares are its chapter 27, vimsopaka bala its chapter 7, the trimsamsa lords chapter 6, the benefics and malefics chapter 2, the chara karakas chapter 32, the baladi avasthas chapter 45 and planetary war chapter 79.',
   'A Santhanam volume carries two kinds of text and only one of them is Parashara. The translated shloka is the text; the Notes underneath it are Santhanam''s own commentary, often excellent and sometimes citing works the sage could not have known. Several of the disagreements listed under Where the teachings differ are between Parashara and his translator rather than between two classical authorities, which is a much weaker thing, and where a note adds a rule the verse does not contain this site does not apply it.',
   'Mantreswara''s Phaladeepika, in V. Subrahmanya Sastri''s translation. Independent of Parashara and of roughly comparable standing. It is brief on this subject - the whole treatment is Adhyaya IV, and its last sloka sends the reader to the translator''s own edition of Sripatipaddhati for anything further - but brevity is not the point. Its value is that it is a second witness: where it agrees with Parashara a reading has two independent sources, and where it agrees with Parashara against Raman, as it does on the Sun''s requirement, that is the strongest case any objection to this site''s figures has.',
   'B. V. Raman''s Graha and Bhava Balas. The standard English working of chapter 27 and the book this site actually computes from. What makes it the operative authority is not its age but that it is worked: every rule arrives with a numbered example for a single Standard Horoscope, so a question about what Raman meant is answered by a figure he printed rather than by argument. Where the verses are terse - and chapter 27 is very terse - he is the one who had to make them compute, and an implementer inherits that problem rather than the sage''s freedom to leave it open.',
   'So the precedence runs: Parashara''s verse first; Raman where the verse is silent, ambiguous, or could not have anticipated the question; Santhanam''s notes last, and only where nothing contradicts them. Phaladeepika is a check on the first rather than a fourth vote. The Sun''s requirement is the single place this site overrides that order, for a reason given in full where the choice is described.',
   'Raman''s other two books cover what falls outside chapter 27: Hindu Predictive Astrology for the combustion orbs at section 54 and for the nodal exaltations, and Three Hundred Important Combinations for the yogas.',
   'Sripathi is behind more of this than his name suggests. The drishti curve this site uses is his, reaching it through Raman''s sections 114 and 115; Mantreswara points at the same work for the arithmetic his own chapter leaves out; and the translator of Phaladeepika is also the translator of Sripatipaddhati. Two independent chains run back to one book, and it repays going to directly: its account of the eight motions is the one that makes sense of the garbled list in the translations of Parashara, and it supplies a boundary those translations leave out. The drishti curve is the part still taken at second hand.',
   'Saravali is cited only where Santhanam cites it - the Yavana band for the Moon''s nature is his report of his own translation, page 70, not a reading this site checked. Kalyana Varma''s text has not been consulted directly and nothing here should be taken as evidence of what it says.',
   'Light on Life, by Hart de Fouw and Robert Svoboda, is the odd one out and is here for what it declines to do. It lays out dignity, combustion and the avasthas carefully and stops short of shadbala''s arithmetic, on the ground that a single number invites being read as a verdict on a graha. That objection is not answered by computing the number more accurately, and it is the reason the first passage in this section is about what strength does not mean.'
 ],
 'Where each of these choices actually bites is set out under Where the teachings differ.',
 'Santhanam''s Brihat Parashara Hora Shastra, Raman''s Graha and Bhava Balas, Hindu Predictive Astrology and Three Hundred Important Combinations, Subrahmanya Sastri''s Phaladeepika, and de Fouw and Svoboda''s Light on Life, in those editions. Section and page numbers throughout were checked against the texts rather than taken from secondary summaries; where a work is cited at second hand, as Saravali is and as Sripatipaddhati was until its cheshta chapter was read here directly, the passage says so.',
 714),

-- The three below are the ones that are hard to get anywhere else. Disagreements
-- between authorities are at least written down somewhere; the clocks kala bala
-- runs on, and the errors an implementation actually makes, are not, and every
-- trap listed under 'traps' was in this site's own code first.

('strength', 'Kala bala', 'clocks',
 'The four clocks kala bala runs on',
 array[
   'Kala bala looks like one measure of time and is really four different reckonings of it, wearing one name. More disagreement between calculators comes from this than from any point of doctrine, because two of the four are easy to get wrong without anything looking wrong.',
   'Apparent solar time, for nata-unnata. The hour angle of the true Sun at the birthplace: nothing at its lower meridian, twelve at its upper. Not zone time, which is an administrative band, and not mean time, which the equation of time parts from the Sun by up to sixteen minutes either way. Raman asks for both corrections by name at section 48.',
   'Sunrise to sunrise, for the vara, the hora and the tribhaga. "The Hindu day begins with sunrise and continues till next sunrise," section 69. So a birth at three in the morning belongs to the previous weekday, and about a quarter of all births fall in that window. The hora is then counted in equal hours from that sunrise, the first ruled by the lord of the weekday.',
   'That the hora is an equal hour is one of the few things all three authorities state outright and none qualifies. Raman: "A hora is equal to 1/24th part of a day." Santhanam: "Each day from sunrise to sunrise is divided into 24 equal parts of one hour or 2.5 Ghatika." Charak, citing Aryabhata: "There are 24 Horas in a day, each Hora being (approximately!) equivalent to an hour." The older planetary-hour scheme, twelve by day and twelve by night, is a different thing wearing the same name, and some software uses it here; the two can hand the sixty virupas to different grahas, which on one chart checked gave Mars against Jupiter. Chart settings offers both and defaults to the equal hour.',
   'A year and month that are not astronomical at all, for abda and masa bala. Raman is blunt at section 59: "The Hindus, for astrological purposes, consider a year and month of 360 and 30 days respectively. They are neither solar, nor lunar, nor luni-solar." Both are pure arithmetic on the ahargana, the days elapsed since Creation - divide by 360 or by 30, take the whole quotient, advance the weekday by 3 or by 2 per period, and the lord of the resulting weekday takes the bala.',
   'Reading those two as solar periods is the easy mistake, and this site made it: it computed the Sun''s ingress into Aries and into its current sign, which sounds like the same quantity and is not. It gave the wrong lord in 86% of charts for each, worth 15 and 30 virupas.',
   'And two that are not clocks at all. Paksha bala reads the elongation of the Moon from the Sun, and ayana bala reads declination. Both are positions rather than times, which is worth noticing, because a calculator can have every clock right and still differ here for quite separate reasons.',
   'The practical upshot: two programs that agree on every planetary position to the arcsecond can still differ by more than a rupa on kala bala alone, purely on which clock each part is read by. If your kala bala disagrees with this page, check the clocks before checking the arithmetic.'
 ],
 'Yuddha bala joins this group as a ninth part when there is a war, and is set out separately.',
 'B. V. Raman, Graha and Bhava Balas: section 47 and 48 for nata-unnata and its clock, 52 to 55 for paksha, 56 and 57 for tribhaga, 58 to 67 for the ahargana and the year, month and weekday lords, 68 to 70 for the hora, 71 to 75 for ayana. Brihat Parashara Hora Shastra ch.27 vv.6-13, tr. R. Santhanam.',
 710),

('strength', 'Shadbala', 'traps',
 'Six ways to get it wrong that have nothing to do with the texts',
 array[
   'Everything under Where the teachings differ is a disagreement between authorities, and a calculator on either side of one is defensible. What follows is a different kind of thing: plain errors, where no text supports the result and the answer is simply wrong. They are set out because each is easy to make, hard to see, and produces figures that look like a school rather than a bug. Every one of them was in this site''s own code first.',
   'The sunrise that belongs to another day. Finding which day a moment falls in means converting universal time to local time, and the longitude term that does it is easy to sign backwards. The search window then lands twice the longitude away and returns a neighbouring day''s sunrise. Here it meant that at Delhi every birth between dawn and about half past ten got the previous day''s; at New York, where the error pushes the other way, most of the day was wrong; and at Sydney more than half of all charts changed when it was corrected. It corrupts tribhaga bala, which then scores a mid-morning birth as the third part of the night, and hora bala, which counts hours from it. To catch it: walk a whole local day and check the sunrise never sits more than twenty-four hours from the moment asked about, and never takes more than two distinct values. Asserting only that sunrise precedes sunset will not do it, because when the window is wrong they are both wrong together and the order between them survives.',
   'The vara that begins at midnight. Taking the weekday from the civil date rather than from the sunrise that opened the day. It is wrong for about a quarter of all births, and it is expensive: vara bala''s 45 virupas go to the wrong graha, and because the hora sequence starts from the weekday lord, hora bala''s 60 follow them. Correcting it here moved roughly 30% of charts by 8 virupas on average. To catch it: step through a day and check the vara turns over exactly once, at sunrise, rather than at midnight or at any fixed hour.',
   'Half of one method joined to half of another. This site ran Raman''s 24 and 48 against a true declination that included the Moon''s ecliptic latitude, which is neither author''s method and cost her about 3.9 virupas.',
   'The account given here of why that was wrong was itself wrong, which is the more useful half of the story. It said 24 is what a declination reaches when computed from a longitude alone, and that Parashara''s 23.45 therefore belonged with the true declination. Both halves are backwards. 23 degrees 27 minutes is the obliquity, and a longitude-derived declination is bounded by the obliquity exactly - so it is Parashara''s constant that pairs with it, and the pairing can be checked rather than argued: only that one runs from nought to sixty without leaving the scale.',
   'To catch this kind of error: a constant and the quantity it scales are a matched pair, and the pairing usually has a consequence you can compute. Ask what the formula''s own bounds are, feed it every chart you have, and see which combinations stay inside them.',
   'A proxy standing in for a defined quantity. Cheshta bala is defined from the chesta kendra, the graha''s distance from its seeghrocha. Reading its speed instead seems equivalent, because both are about motion and both peak near retrogression, and for the outer three it very nearly is. It fails completely for the inner two, which turn retrograde at inferior conjunction where a speed reading calls them fast and direct. On one chart the proxy gave Venus 3.9 where the kendra gives 28.7. To catch it: test the case the proxy is least like the thing, not the case it resembles most.',
   'A dignity reached only through a door it does not have. Six of the seven grahas have their moolatrikona inside a sign they own, so a program can test ownership first and ask about moolatrikona afterwards and be right six times. The Moon is the exception: hers is Taurus 3 to 30, and Taurus is Venus''s. Gating the question behind ownership cost her the 45 and gave her a relation to Venus instead, 30 virupas short, in about one chart in thirteen. Raman''s worked example cannot catch it, his Moon being in Aquarius; it took an outside calculator disagreeing by exactly 30 on one graha. To catch it: check the odd one out by hand rather than the rule that covers the majority.',
   'A period that sounds astronomical and is not. Abda and masa bala go to the lords of the weekdays the astrological year and month opened on, and both are counted arithmetically from the ahargana, on a year of 360 days and a month of 30. Computing an actual solar ingress instead is a reasonable guess from the names, produces plausible-looking weekdays, and is wrong: here it misassigned the year lord in 86% of charts and the month lord in 86%, and one or the other in 98%. To catch it: both Raman and Santhanam work examples, 66 years apart and from different epochs, and the ahargana carries its own check - taken modulo 7 it must land on the weekday the birth actually fell on.',
   'What all six have in common is the reason they survived: none was visible in a total. Each was smaller than the tolerance of every figure it fed into, or wrong only for some birth times and not the ones anybody checked. A constant taken from a book should be tested against that book''s own worked example, at the level it is stated, rather than against a sum four steps downstream of it.'
 ],
 'Two of these were found only by asking which text supports each figure, one at a time.',
 'The failures are this site''s own and the corrections are in its history; the rules they failed to follow are B. V. Raman, Graha and Bhava Balas §§69, 75 and 105-107. The percentages were measured on this engine over thousands of charts at Delhi, New York and Sydney, and are properties of this implementation.',
 715),

('strength', 'Shadbala', 'checking',
 'If your figures disagree with ours, in the order worth checking',
 array[
   'Shadbala figures from two programs rarely match, and the reason is almost never that one of them cannot add up. It is that a dozen decisions sit between a birth moment and a total, and the two made different ones. This is the order to check them in, largest cause first, which is not the order anyone naturally guesses.',
   'The ayanamsa, before anything else. It shifts every longitude, and between Lahiri and Raman''s the gap is 1.44 degrees: 19 shashtiamsas on the average total, as much as three rupas, 7% of strong-or-weak verdicts turned over, and a graha in a different sign in 9% of readings. It is larger than every doctrinal difference below put together. If you are checking against Raman''s own book, his ayanamsa is the one to set, not Lahiri.',
   'Then the saptavargaja ladder, worth about 5 shashtiamsas and one verdict in forty. Raman halves at each step down from an own sign; Parashara''s verse does not. Neither is a mistake.',
   'Then cheshta bala, where a speed proxy and the chesta kendra agree closely on Jupiter and Saturn and not at all on Venus. If the outer grahas match and Venus is wildly out, this is the reason and no further search is needed.',
   'Then the Moon''s nature, which decides her group for paksha bala and her sign for drik bala, and so shows up twice. A boundary at opposition and a boundary at the eighth day disagree in half of all charts.',
   'Then Mercury''s, where a same-sign test against the Sun and a combustion test disagree in 41% of charts, in both directions.',
   'Then the clock behind nata-unnata, worth three virupas at Delhi and fourteen at the western edge of a wide timezone. Then drik bala, where one translation adds a clause for Mercury and Jupiter worth about 41 virupas and another does not - and where, before assuming a difference of reading, it is worth computing the ceiling the definition allows, since a figure above it cannot be drik bala at all. Then, in the one chart in twelve that holds a planetary war, yuddha bala, where the raw difference and Raman''s division by disc diameters are not remotely the same correction.',
   'Only after all of those is it worth suspecting arithmetic. And if it does come to that, the first places to look are not the formulae but the clocks: which day a sunrise belongs to, and whether the vara turns at sunrise or at midnight. Both were wrong here, both were invisible in the totals, and both are set out under Six ways to get it wrong.',
   'One consequence of all this is worth stating plainly. A figure quoted without the ayanamsa and the authority it was computed under cannot be checked by anybody, including the person who produced it.'
 ],
 null,
 'The readings being chosen between are Parashara''s, in R. Santhanam''s translation, against B. V. Raman''s in Graha and Bhava Balas, with Mantreswara''s Phaladeepika as a third witness on the Sun''s requirement; each is set out under Where the teachings differ. The ayanamsa is chosen in Chart settings and the implementation errors are under Six ways to get it wrong. Every figure quoted was measured on this site''s own engine.',
 716)

on conflict (topic, subject, condition) do update set
  heading = excluded.heading,
  points = excluded.points,
  note = excluded.note,
  source = excluded.source,
  sort_order = excluded.sort_order,
  updated_at = now();
