/**
 * Builds data/cities.js from the GeoNames "cities5000" dump.
 *
 *   curl -O https://download.geonames.org/export/dump/cities5000.zip
 *   curl -O https://download.geonames.org/export/dump/admin1CodesASCII.txt
 *   curl -O https://download.geonames.org/export/dump/countryInfo.txt
 *   unzip cities5000.zip
 *   node scripts/build-cities.mjs <dir-with-those-files>
 *
 * Output is a plain .js file (not .json) on purpose: a <script> tag works when
 * index.html is opened straight off the disk, while fetch() of a local JSON is
 * blocked by the file:// origin rules.
 *
 * Data: GeoNames, CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const src = process.argv[2] || '.';
const out = process.argv[3] || new URL('../data/cities.js', import.meta.url).pathname;

const admin1 = new Map();
for (const line of readFileSync(join(src, 'admin1CodesASCII.txt'), 'utf8').split('\n')) {
  const f = line.split('\t');
  if (f.length >= 2) admin1.set(f[0], f[1]);
}

const countries = new Map();
for (const line of readFileSync(join(src, 'countryInfo.txt'), 'utf8').split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const f = line.split('\t');
  if (f[0] && f[4]) countries.set(f[0], f[4]);
}

const regions = [];   const regionIdx = new Map();
const nations = [];   const nationIdx = new Map();
const zones = [];     const zoneIdx = new Map();
const intern = (list, idx, value) => {
  if (!idx.has(value)) { idx.set(value, list.length); list.push(value); }
  return idx.get(value);
};

const rows = [];
for (const line of readFileSync(join(src, 'cities5000.txt'), 'utf8').split('\n')) {
  if (!line) continue;
  const f = line.split('\t');
  const [, name, ascii, , lat, lon] = f;
  const cc = f[8], a1 = f[10], pop = +f[14], tz = f[17];
  if (!name || !lat || !lon || !tz) continue;
  rows.push({
    name,
    ascii: ascii && ascii !== name ? ascii : '',
    region: intern(regions, regionIdx, admin1.get(`${cc}.${a1}`) || ''),
    nation: intern(nations, nationIdx, countries.get(cc) || cc),
    zone: intern(zones, zoneIdx, tz),
    lat: (+lat).toFixed(4).replace(/0+$/, '').replace(/\.$/, ''),
    lon: (+lon).toFixed(4).replace(/0+$/, '').replace(/\.$/, ''),
    pop: Number.isFinite(pop) ? Math.round(pop / 1000) : 0, // thousands, for ranking
  });
}

// Biggest cities first: search scoring uses row order as the tie-breaker, so the
// obvious "Delhi" beats the obscure one without any extra bookkeeping.
rows.sort((a, b) => b.pop - a.pop);

const packed = rows
  .map((r) => [r.name, r.ascii, r.region, r.nation, r.zone, r.lat, r.lon, r.pop].join('|'))
  .join('\n');

writeFileSync(
  out,
  '// Generated by scripts/build-cities.mjs from GeoNames cities5000 (CC BY 4.0).\n' +
    '// Columns: name|asciiName|regionIdx|nationIdx|zoneIdx|lat|lon|populationInThousands\n' +
    'window.CITY_DB = {\n' +
    `  regions: ${JSON.stringify(regions)},\n` +
    `  nations: ${JSON.stringify(nations)},\n` +
    `  zones: ${JSON.stringify(zones)},\n` +
    `  rows: ${JSON.stringify(packed)}\n` +
    '};\n'
);

console.log(`${rows.length} cities, ${regions.length} regions, ${nations.length} nations, ${zones.length} zones`);
